server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: qualsiasi rotta non-file rimanda a index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
